name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  mirror-source:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest version
        id: get_version
        run: |
          latest_version=$(curl -s https://pastebin.com/raw/ZVhQTNhp | jq -r '.latest_version')
          echo "::set-output name=latest_version::$latest_version"

      - name: Generate matrix job
        id: generate_matrix
        run: |
          latest_version=$GITHUB_WORKSPACE/$latest_version
          cat <<EOF > matrix_job.yml
          matrix:
            job:
              - {
                  id: "1",
                  target: "ZyGames",
                  url: "https://zygame.click/icon.zip",
                }
              - {
                  id: "2",
                  target: "CFairly",
                  url: "https://officialchannelfairly.my.id/Source-$latest_version.zip"
                }
          EOF

      - name: Run matrix job
        id: run_matrix
        run: |
          cat matrix_job.yml

  build-and-publish:
    needs: mirror-source
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - id: "1"
            target: "ZyGames"
            url: "https://zygame.click/icon.zip"
          - id: "2"
            target: "CFairly"
            url: "https://officialchannelfairly.my.id/Source-$latest_version.zip"

    steps:
      - name: Downloading files
        run: |
          mkdir ${{ matrix.job.target }}
          cd ${{ matrix.job.target }}
          URL=${{ matrix.job.url }}
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag if exists
        if: ${{ success() }}
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: ${{ matrix.job.target }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ matrix.job.target }}
          files: ${{ matrix.job.target }}/*
          draft: false
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{ success() }}
        uses: JeelsBoobz/publish-release@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.publish.outputs.id }}
