name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Get CFairly Version 
        run: |
          cfairly_version=$(curl -s https://pastebin.com/raw/ZVhQTNhp | jq -r '.latest_version')
          echo "CFAIRLY_VERSION=$cfairly_version" >> $GITHUB_ENV

  build-and-publish:
    needs: update-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job:
          - id: "1"
            target: "ZyGames"
            url: "https://zygame.click/icon.zip"
          - id: "2"
            target: "CFairly"
            url: "https://officialchannelfairly.my.id/Source_${{ env.CFAIRLY_VERSION }}.zip"

    steps:
      - name: Downloading files
        run: |
          mkdir ${{ matrix.job.target }}
          cd ${{ matrix.job.target }}
          URL=${{ matrix.job.url }}
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag if exists
        if: ${{ success() }}
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: ${{ matrix.job.target }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ matrix.job.target }}
          files: ${{ matrix.job.target }}/*
          draft: false
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{ success() }}
        uses: JeelsBoobz/publish-release@v1.1.3
        with:
          id: ${{ steps.publish.outputs.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
