name: Mirror

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
jobs:

  Mirror:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              id: "1",
              target: "ZyGames",
            }
          - {
              id: "2",
              target: "CFairly",
            }

    steps:
      - uses: actions/checkout@v4

      - name: Downloading files
        if: ${{ matrix.job.target=='ZyGames' }}
        run: |
          mkdir ZyGames
          cd ZyGames
          URL="https://zygame.click/icon.zip"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag if exists
        if: ${{ success() && matrix.job.target=='ZyGames' }}
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: ZyGames
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        id: ZyGames
        if: ${{ success() && matrix.job.target=='ZyGames' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ZyGames
          files: ZyGames/*
          draft: false
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{ success() && matrix.job.target=='ZyGames' }}
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.ZyGames.outputs.id }}

      - name: Downloading files
        if: ${{ matrix.job.target=='CFairly' }}
        run: |
          mkdir CFairly
          cd CFairly
          VERSION=$(curl -s https://pastebin.com/raw/ZVhQTNhp | jq -r '.latest_version')
          URL="https://officialchannelfairly.my.id/Source_${VERSION}.zip"
          bash ../download $(basename ${URL}) ${URL}

      - name: Delete tag if exists
        if: ${{ success() && matrix.job.target=='CFairly' }}
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: CFairly
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release
        id: CFairly
        if: ${{ success() && matrix.job.target=='CFairly' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: CFairly
          files: CFairly/*
          draft: false
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{ success() && matrix.job.target=='CFairly' }}
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.CFairly.outputs.id }}
